services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www/new-laravel-project
    volumes:
      - ./new-laravel-project:/var/www/new-laravel-project
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    working_dir: /var/www/new-laravel-project
    volumes:
      - ./new-laravel-project:/var/www/new-laravel-project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - dbdata:/var/lib/mysql

networks:
  laravel:

volumes:
  dbdata:
